### ISSUE TITLE
Incompatible with php without pdo mysql

### ISSUE THREAD

**Issue by codercms** [orchestral/testbench-core#20]
This package now uses constant (PDO::MYSQL_ATTR_SSL_CA) that only available with PHP PDO Mysql extension - https://github.com/orchestral/testbench-core/blob/3.8/laravel/config/database.php#L63

So on PHP without pdo mysql ext tests will fail (Error: Undefined class constant 'MYSQL_ATTR_SSL_CA')

**Comment by codercms** [comment]
Possible fix is - define constant if it's not defined or remove this constant.

**Comment by crynobone** [comment]
How are you handling the default Laravel skeleton in this case?

**Comment by codercms** [comment]
@crynobone it's just a standard test:
```php
use PHPUnit\Framework\TestCase;

/**
 * Class EmailMessageTest
 * @package Nexus\Client\Notify\Tests
 */
class EmailMessageTest extends TestCase
{
     public function testSomething(): void
     {
             //
     }
}
```

**Comment by crynobone** [comment]
The skeleton is going to be introduced in Laravel default installation, see <https://github.com/laravel/laravel/blob/develop/config/database.php#L58>. So again how you use plan to handle that when Laravel by default include this.

**Comment by codercms** [comment]
It will be great if this package can offer ability to override Laravel's default config files.
If we can override Laravel's default config files than we can avoid this issue.

**Comment by crynobone** [comment]
I would recommend you manage your own skeleton folder and set the base path location to it.

See <https://github.com/orchestral/testing/blob/master/src/TestCase.php#L58-L66> for example.

**Comment by codercms** [comment]
@crynobone got it, thanks

**Comment by crynobone** [comment]
Okay, I'm starting to have doubt about the added `options` requirement for testing. But for not I'm going to wait for more feedback from the community.

**Comment by quetzyg** [comment]
I also get this issue when testing a package, not a Laravel project. With version 3.7 everything works as it should.

**Comment by codercms** [comment]
I think all of non mysql users having this trouble.

**Comment by quetzyg** [comment]
Works a charm. Now we're just missing the `v3.8.0` tag :)
