### ISSUE TITLE
v3.8 is not tagged

### ISSUE THREAD

**Issue by axelitus** [orchestral/testbench-core#21]
Version 3.8 is not tagged, so `orchestra/testbench:~3.8.` cannot be used yet as it's a requirement.

**Comment by axelitus** [comment]
For those of you who need it, a workaround:

Add `"orchestral/testbench-core": "3.8.x-dev"` to your `require` or `require-dev` configuration.

**Comment by francislavoie** [comment]
FYI @crynobone

**Comment by crynobone** [comment]
> cannot be used yet as it's a requirement.

How `laravel/framework` manage to release `v5.8.0` when `orchestra/testbench-core` hasn't release yet? They don't use `@dev` because they set `"minimum-stability": "dev"` and if you like stable version you can add `"prefer-stable": true`.

**Comment by francislavoie** [comment]
Thanks for tagging a release! Composer update with `orchestra/testbench` 3.8 works now :smile:

**Comment by axelitus** [comment]
You are right @crynobone, that was poor writing from me. It could be used as you say, just not as a tagged release.

The thing is I was sending a pull-request for a package that has none of those entries in their config and I did not want to include them, therefore the automated tests in Travis failed. I still think the best solution was to tag the release though ;) so thanks for that!

**Comment by crynobone** [comment]
`orchestra/testbench-core` is a dev dependencies, and at all time it's being used by Laravel Framework to tests the core even up to `dev-master` (`5.9`). Tag or no tag I been always making sure that we are prepared for any changes to Laravel so as package developers you can also prepare for the upcoming release earlier without having to wait until the core team tag `v5.8.0`.

**Comment by neyl** [comment]
Thanks for all your hard work!

I think that this tagging is a BC breaker and should have been 4.0
PHPUnit 7.5.6 has 
`protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
`
My composer.json has `"orchestra/testbench": "~3.0",` and now when updating all tests failed due to void return type on setUp

**Comment by crynobone** [comment]
We follow Laravel versioning, and Laravel had to deal with this as well on it's 5.8 release.

**Comment by francislavoie** [comment]
To add onto what was said, I recommend reading https://laravel.com/docs/5.8/releases#versioning-scheme. Laravel does not follow semver. The `~` in composer is for semver: https://getcomposer.org/doc/articles/versions.md#tilde-version-range-

**Comment by crynobone** [comment]
Furthermore you can use `protected function setUp(): void` in lower testbench version. I myself has go as low as Laravel 5.0 (Testbench 3.0) because having a CI that test on every version up to 5.8 isn't realistic.
