### ISSUE TITLE
Undefined variable: guard

### ISSUE THREAD

**Issue by lindyhopchris** [orchestral/testbench-core#22]
On the `3.8` release getting an error: `Undefined variable: guard` on this line:
https://github.com/orchestral/testbench-core/blob/3.8/src/Http/Middleware/RedirectIfAuthenticated.php#L21

**Comment by crynobone** [comment]
can u make a PR?

**Comment by lindyhopchris** [comment]
If I have time to slot it in around other work today I can. What's the purpose of that class, to be identical to this one:
https://github.com/laravel/laravel/blob/master/app/Http/Middleware/RedirectIfAuthenticated.php

**Comment by crynobone** [comment]
yes, except the namespace

**Comment by codercms** [comment]
@crynobone here is PR - https://github.com/orchestral/testbench-core/pull/23

**Comment by lindyhopchris** [comment]
@crynobone thanks!

**Comment by crynobone** [comment]
Will release a new tag today.
