### ISSUE TITLE
Please merge 4.x -> master

### ISSUE THREAD

**Issue by GrahamCampbell** [orchestral/testbench-core#35]
So that https://github.com/GrahamCampbell/Laravel-TestBench/pull/25 can pass. :)

I can submit a PR to do it if you like.

**Comment by crynobone** [comment]
One minute

**Comment by crynobone** [comment]
Done

**Comment by GrahamCampbell** [comment]
🎉 

Could you do the same on the testbench repo please. That's actually the one I need (as well). Sorry!

**Comment by GrahamCampbell** [comment]
Oh, I see you have. 🚀
