### ISSUE TITLE
Bug with fzaninotto/faker ^1.4 on PHP 7.4 + prefer-lowest

### ISSUE THREAD

**Issue by arcanedev-maroc** [orchestral/testbench-core#36]
- Testbench Version: 4.5
- Laravel Version: 6.x
- PHP Version: 7.4.x

### Description:

This bug occured when installing `fzaninotto/faker` with composer's flag `prefer-lowest` (using PHP v7.4)

For more details, you can check my tests: https://github.com/ARCANEDEV/LaravelMetrics/pull/4/checks?check_run_id=414671912 

Should be mentioned in `laravel/laravel` & `laravel/framework` repos?

**Comment by crynobone** [comment]
Thanks for the report but I do think this need to be escalated to `laravel` side since I would prefer if we can have similar version constraint for Faker.
