### ISSUE TITLE
Incompatible with laravel/ui?

### ISSUE THREAD

**Issue by itshaydendev** [orchestral/testbench-core#43]
- Testbench Version: `^5.3`
- Laravel Version: `^7.14`
- PHP Version: 7.3.18
- Database Driver & Version: sqlite driver, not causing the issue

### Description:
I'm calling `Auth::routes(['register' => false]);` in my routes file for my package. It's fine on a site using it, but when I try to run it using Testbench, it gives me this issue:

```
RuntimeException: In order to use the Auth::routes() method, please install the laravel/ui package.
```

### Steps To Reproduce:
```php
/** @test */
public function shouldRedirectToLogin(): void
{
  $response = $this->get('/');
  $response->assertRedirect('/login');
}
```

**Comment by itshaydendev** [comment]
I define the environment using a trait, and I extend the regular TestCase class for each test case file.

```php
<?php

namespace MyPackage\Tests;

trait TestCaseEnv
{
    protected function getPackageProviders($app)
    {
        return ['ESPProjects\EIS\EISServiceProvider'];
    }

    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('database.default', 'testbench');
        $app['config']->set('database.connections.testbench', [
            'driver'   => 'sqlite',
            'database' => ':memory:',
            'prefix'   => '',
        ]);
    }

    protected function setUp(): void
    {
        parent::setUp();
    }
}
```

**Comment by crynobone** [comment]
I would think you need to register `Laravel\Ui\UiServiceProvider` as well, right? 

Running on Testbench doesn't look packages registered via package discovery like running from a Laravel installation.

**Comment by itshaydendev** [comment]
Ah, I didn't know it had a service provider. Thanks!
