### ISSUE TITLE
The interface Orchestra\Testbench\Contracts\Laravel and PHP 7.4

### ISSUE THREAD

**Issue by egorsmkv** [orchestral/testbench-core#45]
![Screenshot 2020-08-25 at 22 10 38](https://user-images.githubusercontent.com/7875085/91217228-d57d9100-e71f-11ea-85fb-c81bf3169c80.png)

As you can see from the picture, the IDE says "protected" modifier must be omitted. Also, I can't compile the code with laravel-opcache with these modifiers.

**Comment by crynobone** [comment]
1. That's a recommendation, we kept this file as reference for everyone that want to find what's available for them to extends in a single page.

2. Not sure why you would ever want to opcache a testing helpers.

**Comment by egorsmkv** [comment]
laravel-opcache scans the vendor folder and tries to compile this file as well. I think, it's better to add the file to the exclude section in configuration.

**Comment by egorsmkv** [comment]
Thanks for your help, @crynobone
