### ISSUE TITLE
`WithFactories` uses removed class 

### ISSUE THREAD

**Issue by freekmurze** [orchestral/testbench-core#46]
- Testbench Version: 6.0.0
- Laravel Version: 8.0.0
- PHP Version: 7.4

### Description:

When using `withFactories` an error `Class Illuminate\Database\Eloquent\Factory does not exist` is thrown. The class does not exist anymore in Laravel 8

### Steps To Reproduce:

You'll see this error when using `$this->withFactories($path)` in a test

This error can be avoided when installing `laravel/legacy-factories`, but I think this method should be made to work without requiring the legacy package.

**Comment by crynobone** [comment]
You can refer to https://github.com/orchestral/testbench#class-illuminatedatabaseeloquentfactory-not-found

**Comment by crynobone** [comment]
In the past, we always explicitly tell the developers if there an issue with their setup. E.g <https://github.com/orchestral/testbench-core/blob/3.4/src/Traits/WithLoadMigrationsFrom.php#L21>

I would say we should add the same exception for this case.

**Comment by freekmurze** [comment]
Seems likes a nice approach!

**Comment by crynobone** [comment]
Tagged https://github.com/orchestral/testbench-core/releases/tag/v6.0.1
