### ISSUE TITLE
PHPUnit 9.5 - Call to undefined method getAnnotations()

### ISSUE THREAD

**Issue by reganjohnson** [orchestral/testbench-core#50]
- Testbench Version: 6.x
- Laravel Version: 8.x
- PHP Version: 7.4.x

### Description:
PHPUnit 9.5 was released a few days ago. With this release, they removed the `getAnnotations()` method which is used in `testbench-core` at `\Orchestra\Testbench\Concerns\CreatesApplication::resolveApplicationBootstrappers`.

See: https://github.com/sebastianbergmann/phpunit/compare/9.4.4...9.5.0#diff-75a3eeca974a0ce169359a31becc86004ea431fb1811f13e1ff04b06fb926aeaL941

**Comment by crynobone** [comment]
`v4.9.1`, `v5.9.1` and `v6.6.1` should already solved this.
