### ISSUE TITLE
Bug isArray() is deprecated in  php 8 

### ISSUE THREAD

**Issue by mehdi-fathi** [orchestral/testbench-core#51]
- Testbench Version: 6
- Laravel Version: 7
- PHP Version: 8
- Database Driver & Version:

### Description:
I think testbench-core doesn't math very much with PHP 8. I had error : `ErrorException: Method ReflectionParameter::isArray() is deprecated` when I started test case in PHP 8.

### Steps To Reproduce:
Please update the package with PHP 8.

**Comment by crynobone** [comment]
Can you provide the failing tests

**Comment by mehdi-fathi** [comment]
@crynobone all of the tests were failing. all of them show error : `ErrorException: Method ReflectionParameter::isArray() is deprecated`. Error show filoe orchestra/testbench-core/src/Concerns/WithLoadMigrationsFrom.php:28 in testbench

**Comment by crynobone** [comment]
1. We already tested testbench with PHP 8 and it's not failing. 
2. Not of the mentioned code uses `ReflectionFunction`. 

You should describe the issue or create a PR with failing tests.

**Comment by mehdi-fathi** [comment]
@crynobone 
![Screen Shot 1399-09-22 at 10 37 23](https://user-images.githubusercontent.com/11867691/101977875-07cae400-3c66-11eb-922b-46bb680295e6.png)

I used Action github to implement tests in PHP 8.
![Screen Shot 1399-09-22 at 10 38 39](https://user-images.githubusercontent.com/11867691/101977896-3648bf00-3c66-11eb-97ff-c259cc0e78fa.png)

**Comment by crynobone** [comment]
The error occured on Mockery deps, not Testbench.

**Comment by glorand** [comment]
https://github.com/mockery/mockery/issues/1071 still we have the issue. Probably you have to upgrade the mockery package

**Comment by glorand** [comment]
@crynobone Check this test action on github: https://github.com/glorand/laravel-model-settings/runs/1548652988?check_suite_focus=true
